Feature/layout
DarleiSilvva/Projeto_final_Game_Catalog pull request #5
Opened 2021-05-31 19:08 UTC by DarleiSilvva

Foi realizada a inserção do layout, implementação dos fragments  e bottom model.

2021-05-31 20:46 UTC, Lhmsouza requested changes

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".TestActivity"></activity>
Como não tem nenhum elemento interior da `<activity>...</activity>`, poderia deixar só como `<activity.../>`, o que acha?

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/FavoriteFragment.kt
> +            ViewModelProvider(this).get(FavoriteViewModel::class.java)
Poderia usar o koin pra receber essa `ViewModel` no fragment. Lembra como se fazer pra injetar dependências de view model?

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/FavoriteFragment.kt
> +        val textView: TextView = binding.textFavorite
Tu acha que fica muito necessário criar essas duas variáveis? `root` e `textView`? Em vez de usar direto `binding.root` e `binding.textFavorite`.

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/FavoriteFragment.kt
> +    private val binding get() = _binding!!
Se retirar o `get()`, não continua funcionando?

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/GamesFragment.kt
> +    private val binding get() = _binding!!
Se retirar o `get()`, não continua funcionando?

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/java/caatsoft/studio/com/gamecatalog/viewmodel/GamesViewModel.kt
> +class GamesViewModel (private val repository: Repository) : ViewModel(), KoinComponent {
Acredito que não precise mais herdar de `KoinComponent`, posso ter me enganado, mas dá uma conferida se impacta tirar isso.

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.TestTwo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
O nome `TestTwo` é intencional?

2021-05-31 20:46 UTC, Lhmsouza commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.TestTwo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
O nome `TestTwo` é intencional?

2021-06-01 02:44 UTC, DarleiSilvva commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".TestActivity"></activity>
Nesse caso eu preciso do "Theme.GameCatalog" porque eu acrescentei uma fontFamily "bangers" e um  windowBackground lilás no projeto.

2021-06-01 02:46 UTC, DarleiSilvva commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.TestTwo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
Era um teste que eu estava fazendo aqui, mas não é intencional ficar.

2021-06-01 02:46 UTC, DarleiSilvva commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.TestTwo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
Era um teste que eu estava fazendo aqui, mas não é intencional ficar.

2021-06-01 04:02 UTC, DarleiSilvva commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/FavoriteFragment.kt
> +    private val binding get() = _binding!!
Funciona, mas dá um delay quando muda de fragment.

2021-06-01 04:03 UTC, DarleiSilvva commented on app/src/main/java/caatsoft/studio/com/gamecatalog/ui/GamesFragment.kt
> +    private val binding get() = _binding!!
Funciona, mas dá um delay quando muda de fragment.

2021-06-01 04:04 UTC, DarleiSilvva commented on app/src/main/java/caatsoft/studio/com/gamecatalog/viewmodel/GamesViewModel.kt
> +class GamesViewModel (private val repository: Repository) : ViewModel(), KoinComponent {
Funciona realmente sem problemas.

2021-06-01 17:16 UTC, merged